/*
 * About.java
 *
 * Created on 15. Juni 2005, 15:42
 */

package GUI;

public class About extends javax.swing.JDialog {
    
    /** Creates new form About */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Arial", 0, 10));
        setForeground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_400x259.jpg")));
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 324));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 324));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 324));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 0, 400, 260);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(390, 330, 90, 29);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Easy Ferienwohnung Verwaltung");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 270, 490, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel3.setText("V 0.99");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 310, 80, 20);

        jLabel4.setText("(c) by Jan-Lars Linke, Marc Nordhausen, Matthias Gose, Martin Hieckmann");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 370, 470, 14);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    
}
