/*
 * ImmobiErfassenDIA.java
 *
 * Created on 25. Mai 2005, 23:22
 */

package GUI;
import FK.*;
import javax.swing.*;

public class ImmobilieErfassenDIA extends javax.swing.JDialog {
    
    /** Creates new form ImmobiErfassenDIA */
    public ImmobilieErfassenDIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(500, 300);
        this.setVisible(true);               
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPopupMenu1 = new javax.swing.JPopupMenu();
        strasseLabel = new javax.swing.JLabel();
        ortLabel = new javax.swing.JLabel();
        abbrechenBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        mietobjektLabel = new javax.swing.JLabel();
        objektlNrLabel = new javax.swing.JLabel();
        plzText = new javax.swing.JTextField();
        personalNrText = new javax.swing.JTextField();
        strasseText = new javax.swing.JTextField();
        ortText = new javax.swing.JTextField();
        einzelzimmerLabel = new javax.swing.JLabel();
        doppelzimmerLabel = new javax.swing.JLabel();
        zweibettzimmerLabel = new javax.swing.JLabel();
        einzelzimmerText = new javax.swing.JTextField();
        doppelzimmerText = new javax.swing.JTextField();
        zweibettzimmerText = new javax.swing.JTextField();
        Tagespreis = new javax.swing.JLabel();
        tagespreisText = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        strasseLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        strasseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        strasseLabel.setText("Strasse:");
        getContentPane().add(strasseLabel);
        strasseLabel.setBounds(100, 70, 50, 15);

        ortLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ortLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ortLabel.setText("PLZ / Ort:");
        getContentPane().add(ortLabel);
        ortLabel.setBounds(90, 90, 60, 15);

        abbrechenBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        abbrechenBTN.setText("Abbrechen");
        abbrechenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrechenBTNActionPerformed(evt);
            }
        });

        getContentPane().add(abbrechenBTN);
        abbrechenBTN.setBounds(110, 230, 110, 23);

        okBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        getContentPane().add(okBTN);
        okBTN.setBounds(300, 230, 110, 23);

        mietobjektLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        mietobjektLabel.setText("Mietobjekt");
        getContentPane().add(mietobjektLabel);
        mietobjektLabel.setBounds(10, 10, 140, 17);

        objektlNrLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        objektlNrLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        objektlNrLabel.setText("Objekt-Nr:");
        getContentPane().add(objektlNrLabel);
        objektlNrLabel.setBounds(40, 40, 100, 15);

        plzText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(plzText);
        plzText.setBounds(160, 90, 60, 20);

        personalNrText.setEditable(false);
        personalNrText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(personalNrText);
        personalNrText.setBounds(160, 40, 60, 20);

        strasseText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(strasseText);
        strasseText.setBounds(160, 70, 260, 20);

        ortText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(ortText);
        ortText.setBounds(220, 90, 200, 20);

        einzelzimmerLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        einzelzimmerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        einzelzimmerLabel.setText("Einzelzimmer:");
        getContentPane().add(einzelzimmerLabel);
        einzelzimmerLabel.setBounds(70, 160, 90, 15);

        doppelzimmerLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        doppelzimmerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        doppelzimmerLabel.setText("Doppelzimmer:");
        getContentPane().add(doppelzimmerLabel);
        doppelzimmerLabel.setBounds(190, 160, 100, 14);

        zweibettzimmerLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        zweibettzimmerLabel.setText("Zweibettzimmer:");
        getContentPane().add(zweibettzimmerLabel);
        zweibettzimmerLabel.setBounds(330, 160, 100, 15);

        einzelzimmerText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(einzelzimmerText);
        einzelzimmerText.setBounds(170, 160, 30, 20);

        doppelzimmerText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(doppelzimmerText);
        doppelzimmerText.setBounds(290, 160, 30, 20);

        zweibettzimmerText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(zweibettzimmerText);
        zweibettzimmerText.setBounds(430, 160, 30, 20);

        Tagespreis.setFont(new java.awt.Font("Tahoma", 0, 12));
        Tagespreis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Tagespreis.setText("Tagespreis:");
        getContentPane().add(Tagespreis);
        Tagespreis.setBounds(270, 40, 70, 15);

        tagespreisText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(tagespreisText);
        tagespreisText.setBounds(350, 40, 70, 20);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        int inr = 0;
        try
        {
            float tagespreis = Float.parseFloat(tagespreisText.getText());
            String strasse = strasseText.getText();
            String plz = plzText.getText();
            String ort = ortText.getText();

            int einzelzimmer = Integer.parseInt(einzelzimmerText.getText());
            int doppelzimmer = Integer.parseInt(doppelzimmerText.getText());
            int zweibettzimmer = Integer.parseInt(zweibettzimmerText.getText());        
        
            Mietobjekt einMietobjekt = new Mietobjekt(einzelzimmer, doppelzimmer, zweibettzimmer, strasse, plz, ort, tagespreis);
            inr = einMietobjekt.Speichern();
        }
        catch(Exception e)
        {
           inr = -1; 
        }
        finally
        {
            if(inr!=-1)
            {
                JOptionPane.showMessageDialog(this, "Immobielie wurde erfolgreich mit der ImmobielienNr. "+inr+" angelegt", "OK", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();  
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Immobielie konnte nicht angelegt werden. \nBitte kontrollieren Sie die eingegebenden Daten", "Error", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_okBTNActionPerformed

    private void abbrechenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbrechenBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_abbrechenBTNActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tagespreis;
    private javax.swing.JButton abbrechenBTN;
    private javax.swing.JLabel doppelzimmerLabel;
    private javax.swing.JTextField doppelzimmerText;
    private javax.swing.JLabel einzelzimmerLabel;
    private javax.swing.JTextField einzelzimmerText;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel mietobjektLabel;
    private javax.swing.JLabel objektlNrLabel;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel ortLabel;
    private javax.swing.JTextField ortText;
    private javax.swing.JTextField personalNrText;
    private javax.swing.JTextField plzText;
    private javax.swing.JLabel strasseLabel;
    private javax.swing.JTextField strasseText;
    private javax.swing.JTextField tagespreisText;
    private javax.swing.JLabel zweibettzimmerLabel;
    private javax.swing.JTextField zweibettzimmerText;
    // End of variables declaration//GEN-END:variables
    
}
