/*
 * kundenIFrame.java
 *
 * Created on 20. Mai 2005, 20:33
 */

package GUI;
import FK.*;
import java.util.*;
import javax.swing.*;

public class KundenIFrame extends javax.swing.JInternalFrame {
    private startGUI einAufrufer;
    private LinkedList aenderungen = new LinkedList();
            
    /** Creates new form kundenIFrame */
    public KundenIFrame() {
        initComponents();
        this.setVisible(false);
    }
    
    public KundenIFrame(startGUI aufrufer) {
        initComponents();
        einAufrufer = aufrufer;
        this.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        begriffText = new javax.swing.JTextField();
        gruppeComboBox = new javax.swing.JComboBox();
        suchenBTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rechnungenBTN = new javax.swing.JButton();
        buchungenBTN = new javax.swing.JButton();
        bearbeitenBTN = new javax.swing.JButton();
        loeschenBTN = new javax.swing.JButton();
        ausblendenBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kundenTBL = new javax.swing.JTable();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Kunden");
        setMinimumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(800, 640));
        jPanel1.setLayout(new java.awt.BorderLayout());

        begriffText.setMinimumSize(new java.awt.Dimension(11, 23));
        begriffText.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel4.add(begriffText);

        gruppeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KundenNr", "Nachname" }));
        gruppeComboBox.setPreferredSize(new java.awt.Dimension(92, 23));
        jPanel4.add(gruppeComboBox);

        suchenBTN.setText("Suchen");
        suchenBTN.setPreferredSize(new java.awt.Dimension(80, 23));
        suchenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println ("TEST");
                suchenBTNActionPerformed(evt);
            }
        });

        jPanel4.add(suchenBTN);

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jButton1.setText("Neue Reservierung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.add(jButton1);

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        rechnungenBTN.setText("Rechnungen");
        rechnungenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(rechnungenBTN);

        buchungenBTN.setText("Reservierungen");
        buchungenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buchungenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(buchungenBTN);

        bearbeitenBTN.setText("Speichern");
        bearbeitenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bearbeitenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(bearbeitenBTN);

        loeschenBTN.setText("L\u00f6schen");
        loeschenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loeschenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(loeschenBTN);

        ausblendenBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        ausblendenBTN.setIcon(new javax.swing.ImageIcon("Ausblenden"));
        ausblendenBTN.setText("Ausblenden");
        ausblendenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausblendenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(ausblendenBTN);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(800, 560));
        kundenTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kunden Nr", "Nachname", "Vorname", "Geburtsdatum", "Strasse", "PLZ", "Ort", "Telefon Nr"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kundenTBL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                kundenTBLPropertyChange(evt);
            }
        });

        jScrollPane1.setViewportView(kundenTBL);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String knr;
        knr = kundenTBL.getValueAt(kundenTBL.getSelectedRow(), 0).toString();
        einAufrufer.reservierungErfassenAnzeigen(knr); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bearbeitenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bearbeitenBTNActionPerformed
        ListIterator einIterator = aenderungen.listIterator();
        KundenVerwaltung eineVerwaltung = new KundenVerwaltung();
        int kNr, spaltenNr;
        String nachname,vorname,gDatum,strasse,plz,ort,telNr;
        
        while(einIterator.hasNext())
        {
            spaltenNr = Integer.parseInt(einIterator.next().toString());
            if(spaltenNr!=-1)
            {
            kNr = Integer.parseInt(kundenTBL.getValueAt(spaltenNr, 0).toString());
            nachname = kundenTBL.getValueAt(spaltenNr, 1).toString();
            vorname = kundenTBL.getValueAt(spaltenNr, 2).toString();
            gDatum = kundenTBL.getValueAt(spaltenNr, 3).toString();
            strasse = kundenTBL.getValueAt(spaltenNr, 4).toString();
            plz = kundenTBL.getValueAt(spaltenNr, 5).toString();
            ort = kundenTBL.getValueAt(spaltenNr, 6).toString();
            telNr = kundenTBL.getValueAt(spaltenNr, 7).toString();
            eineVerwaltung.update(kNr,nachname,vorname,gDatum,strasse,plz,ort,telNr);
            }
        }
    }//GEN-LAST:event_bearbeitenBTNActionPerformed

    private void kundenTBLPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kundenTBLPropertyChange
        int spaltenNrTMP;
        boolean isVorhanden = false;
        try
        {   spaltenNrTMP = kundenTBL.getSelectedRow();
            
            ListIterator einIterator = aenderungen.listIterator();
            while(einIterator.hasNext())
            {
                if(spaltenNrTMP == Integer.parseInt(einIterator.next().toString()))
                {
                    isVorhanden = true;
                }
            }
            
            if(!isVorhanden)
            {
                aenderungen.add(spaltenNrTMP);
            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_kundenTBLPropertyChange

    private void loeschenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loeschenBTNActionPerformed
        KundenVerwaltung eineVerwaltung = new KundenVerwaltung();
        int i = eineVerwaltung.loeschen(Integer.parseInt(kundenTBL.getValueAt(kundenTBL.getSelectedRow(), 0).toString()));
        suchen();
        if(i==-1)
        {
            JOptionPane.showMessageDialog(this, " Kunde konnte nicht gel�scht werden, \n da noch Reservierungen oder Rechnungen vorliegen! \n Bitte loeschen Sie erst diese!", "Warnung", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_loeschenBTNActionPerformed

    private void buchungenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buchungenBTNActionPerformed
        String knr;
        knr = kundenTBL.getValueAt(kundenTBL.getSelectedRow(), 0).toString();
        einAufrufer.reservierungenAnzeigen(knr ,2);
    }//GEN-LAST:event_buchungenBTNActionPerformed

    private void suchenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suchenBTNActionPerformed
        suchen();
    }//GEN-LAST:event_suchenBTNActionPerformed

    
    private void rechnungenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungenBTNActionPerformed
        String knr;
        knr = kundenTBL.getValueAt(kundenTBL.getSelectedRow(), 0).toString();
        einAufrufer.rechnungenAnzeigen(knr ,1);
    }//GEN-LAST:event_rechnungenBTNActionPerformed

    private void ausblendenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausblendenBTNActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ausblendenBTNActionPerformed
    
    public void setBegriff(String value)
    {
        begriffText.setText(value);
    }
    
    public void setGruppe(int gruppe)
    {
        gruppeComboBox.setSelectedIndex(gruppe);
    }
    
    public void suchen()
    {
        KundenVerwaltung eineVerwaltung = new KundenVerwaltung();
        LinkedList eineListe = null;
       
        if(gruppeComboBox.getSelectedIndex()==0)
        {
            eineListe = eineVerwaltung.SuchenKnr(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==1)
        {
            eineListe = eineVerwaltung.SuchenName(begriffText.getText());
        }

        ListIterator einIterator = eineListe.listIterator();
        int i=0;
        
        // <editor-fold defaultstate="collapsed" desc=" Tabellen Modell ">
        String[] titel = {"Kunden Nr", "Nachname", "Vorname", "Geburtsdatum", "Strasse", "PLZ", "Ort", "Telefon Nr"};
        boolean[] canEdit = {false, true, true, true, true, true, true, true};
        Class[] types = {Integer.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class};
        
        TabellenModell einModell = new TabellenModell(eineListe.size(), titel, canEdit, types);
        kundenTBL.setModel(einModell);
        // </editor-fold>    
        
        while(einIterator.hasNext())
        {
            Kunde einKunde = (Kunde)einIterator.next();
            kundenTBL.setValueAt(einKunde.getKundenNR(),i,0);
            kundenTBL.setValueAt(einKunde.getNachname(), i, 1);
            kundenTBL.setValueAt(einKunde.getVorname(), i, 2);
            kundenTBL.setValueAt(einKunde.getGDate(), i, 3);
            kundenTBL.setValueAt(einKunde.getStrasse(), i, 4);
            kundenTBL.setValueAt(einKunde.getPLZ(), i, 5);
            kundenTBL.setValueAt(einKunde.getOrt(), i, 6);
            kundenTBL.setValueAt(einKunde.getTelefonNr(), i, 7);
            i++;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ausblendenBTN;
    private javax.swing.JButton bearbeitenBTN;
    private javax.swing.JTextField begriffText;
    private javax.swing.JButton buchungenBTN;
    private javax.swing.JComboBox gruppeComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kundenTBL;
    private javax.swing.JButton loeschenBTN;
    private javax.swing.JButton rechnungenBTN;
    private javax.swing.JButton suchenBTN;
    // End of variables declaration//GEN-END:variables
    
}
