/*
 * MitarbeiterErfassenDIA.java
 *
 * Created on 20. Mai 2005, 21:04
 */

package GUI;
import javax.swing.*;
import FK.*;

public class MitarbeiterErfassenDIA extends javax.swing.JDialog {
    
    /** Creates new form MitarbeiterErfassenDIA */
    public MitarbeiterErfassenDIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(500,300);
        this.setVisible(true);
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDialog1 = new javax.swing.JDialog();
        vornameLabel = new javax.swing.JLabel();
        nachnameLabel = new javax.swing.JLabel();
        strasseLabel = new javax.swing.JLabel();
        ortLabel = new javax.swing.JLabel();
        telefonLabel = new javax.swing.JLabel();
        geburtsdatumLabel = new javax.swing.JLabel();
        abbrechenBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        mitarbeiterLabel = new javax.swing.JLabel();
        personalNrLabel = new javax.swing.JLabel();
        plzText = new javax.swing.JTextField();
        nachnameText = new javax.swing.JTextField();
        vornameText = new javax.swing.JTextField();
        personalNrText = new javax.swing.JTextField();
        strasseText = new javax.swing.JTextField();
        telefonVorText = new javax.swing.JTextField();
        ortText = new javax.swing.JTextField();
        gDatumTagText = new javax.swing.JTextField();
        gDatumMonatText = new javax.swing.JTextField();
        gDatumJahrText = new javax.swing.JTextField();
        telefonText = new javax.swing.JTextField();
        

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        vornameLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        vornameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vornameLabel.setText("Vorname:");
        getContentPane().add(vornameLabel);
        vornameLabel.setBounds(80, 70, 60, 15);

        nachnameLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        nachnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nachnameLabel.setText("Nachname:");
        getContentPane().add(nachnameLabel);
        nachnameLabel.setBounds(70, 90, 70, 15);

        strasseLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        strasseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        strasseLabel.setText("Strasse:");
        getContentPane().add(strasseLabel);
        strasseLabel.setBounds(90, 140, 50, 15);

        ortLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ortLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ortLabel.setText("PLZ / Ort:");
        getContentPane().add(ortLabel);
        ortLabel.setBounds(80, 160, 60, 15);

        telefonLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        telefonLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefonLabel.setText("Telefon:");
        getContentPane().add(telefonLabel);
        telefonLabel.setBounds(90, 180, 50, 15);

        geburtsdatumLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        geburtsdatumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        geburtsdatumLabel.setText("Geburtsdatum:");
        getContentPane().add(geburtsdatumLabel);
        geburtsdatumLabel.setBounds(50, 110, 90, 14);

        abbrechenBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        abbrechenBTN.setText("Abbrechen");
        abbrechenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrechenBTNActionPerformed(evt);
            }
        });

        getContentPane().add(abbrechenBTN);
        abbrechenBTN.setBounds(110, 230, 110, 23);

        okBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        getContentPane().add(okBTN);
        okBTN.setBounds(300, 230, 110, 23);

        mitarbeiterLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        mitarbeiterLabel.setText("Mitarbeiter");
        getContentPane().add(mitarbeiterLabel);
        mitarbeiterLabel.setBounds(10, 10, 140, 17);

        personalNrLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        personalNrLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        personalNrLabel.setText("Personalnummer:");
        getContentPane().add(personalNrLabel);
        personalNrLabel.setBounds(40, 40, 100, 15);

        plzText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(plzText);
        plzText.setBounds(160, 160, 60, 20);

        nachnameText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(nachnameText);
        nachnameText.setBounds(160, 90, 260, 20);

        vornameText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(vornameText);
        vornameText.setBounds(160, 70, 260, 20);

        personalNrText.setEditable(false);
        personalNrText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(personalNrText);
        personalNrText.setBounds(160, 40, 60, 20);

        strasseText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(strasseText);
        strasseText.setBounds(160, 140, 260, 20);

        telefonVorText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(telefonVorText);
        telefonVorText.setBounds(160, 180, 60, 20);

        ortText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(ortText);
        ortText.setBounds(220, 160, 200, 20);

        gDatumTagText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(gDatumTagText);
        gDatumTagText.setBounds(160, 110, 30, 20);

        gDatumMonatText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(gDatumMonatText);
        gDatumMonatText.setBounds(190, 110, 30, 20);

        gDatumJahrText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(gDatumJahrText);
        gDatumJahrText.setBounds(220, 110, 40, 20);

        telefonText.setFont(new java.awt.Font("Tahoma", 0, 12));
        getContentPane().add(telefonText);
        telefonText.setBounds(220, 180, 200, 20);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        String nachname = nachnameText.getText();
        String vorname = vornameText.getText();
        String geburtsdatum = gDatumJahrText.getText() + "-" + gDatumMonatText.getText() + "-" + gDatumTagText.getText();
        String strasse = strasseText.getText();
        String plz = plzText.getText();
        String ort = ortText.getText();
        String telefon = telefonVorText.getText()+"/"+telefonText.getText();
        
        Mitarbeiter einMitarbeiter = new Mitarbeiter(nachname, vorname, geburtsdatum, strasse, plz, ort, telefon);
        
        int mnr = einMitarbeiter.Speichern();
        if(mnr!=-1)
        {
            JOptionPane.showMessageDialog(this, "Mitarbeiter wurde erfolgreich mit der MitarbeiterNr. "+mnr+" angelegt", "OK", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();  
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Mitarbeiter konnte nicht angelegt werden. \nBitte kontrollieren Sie die eingegebenden Daten", "Error", JOptionPane.ERROR_MESSAGE); 
        }  
    }//GEN-LAST:event_okBTNActionPerformed

    private void abbrechenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbrechenBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_abbrechenBTNActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abbrechenBTN;
    private javax.swing.JTextField gDatumJahrText;
    private javax.swing.JTextField gDatumMonatText;
    private javax.swing.JTextField gDatumTagText;
    private javax.swing.JLabel geburtsdatumLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel mitarbeiterLabel;
    private javax.swing.JLabel nachnameLabel;
    private javax.swing.JTextField nachnameText;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel ortLabel;
    private javax.swing.JTextField ortText;
    private javax.swing.JLabel personalNrLabel;
    private javax.swing.JTextField personalNrText;
    private javax.swing.JTextField plzText;
    private javax.swing.JLabel strasseLabel;
    private javax.swing.JTextField strasseText;
    private javax.swing.JLabel telefonLabel;
    private javax.swing.JTextField telefonText;
    private javax.swing.JTextField telefonVorText;
    private javax.swing.JLabel vornameLabel;
    private javax.swing.JTextField vornameText;
    // End of variables declaration//GEN-END:variables
    
}
