/*
 * MitarbeiterIFrame.java
 *
 * Created on 20. Mai 2005, 20:48
 */

package GUI;
import FK.*;
import java.util.*;
import javax.swing.*;

public class MitarbeiterIFrame extends javax.swing.JInternalFrame {
private startGUI einAufrufer;
private LinkedList aenderungen = new LinkedList();
    
    /** Creates new form MitarbeiterIFrame */
    public MitarbeiterIFrame() {
        initComponents();
        this.setSize(800,460);
        this.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mitarbeiterTBL = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        begriffText = new javax.swing.JTextField();
        gruppeComboBox = new javax.swing.JComboBox();
        suchenBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bearbeitenBTN = new javax.swing.JButton();
        loeschenBTN = new javax.swing.JButton();
        ausblendenBTN = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mitarbeiter");
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(800, 560));
        mitarbeiterTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Personal Nr", "Nachname", "Vorname", "Geburtsdatum", "Strasse", "PLZ", "Ort", "Telefon Nr", "Aufgabenbereich", "Ist Taetig"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mitarbeiterTBL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mitarbeiterTBLPropertyChange(evt);
            }
        });

        jScrollPane1.setViewportView(mitarbeiterTBL);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        begriffText.setMinimumSize(new java.awt.Dimension(11, 23));
        begriffText.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel1.add(begriffText);

        gruppeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal Nr", "Nachname", "Ist T�tig", "Ist Frei" }));
        gruppeComboBox.setPreferredSize(new java.awt.Dimension(92, 23));
        jPanel1.add(gruppeComboBox);

        suchenBTN.setText("Suchen");
        suchenBTN.setPreferredSize(new java.awt.Dimension(80, 23));
        suchenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suchenBTNActionPerformed(evt);
            }
        });

        jPanel1.add(suchenBTN);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        bearbeitenBTN.setText("Speichern");
        bearbeitenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bearbeitenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(bearbeitenBTN);

        loeschenBTN.setText("L\u00f6schen");
        loeschenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loeschenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(loeschenBTN);

        ausblendenBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        ausblendenBTN.setIcon(new javax.swing.ImageIcon("Ausblenden"));
        ausblendenBTN.setText("Ausblenden");
        ausblendenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausblendenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(ausblendenBTN);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void loeschenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loeschenBTNActionPerformed
        MitarbeiterVerwaltung eineVerwaltung = new MitarbeiterVerwaltung();
        int i = eineVerwaltung.loeschen(Integer.parseInt(mitarbeiterTBL.getValueAt(mitarbeiterTBL.getSelectedRow(), 0).toString()));
        suchen();
        if(i==-1)
        {
            JOptionPane.showMessageDialog(this, "Mitarbeiter konnte nicht gel�scht werden!", "Warnung", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_loeschenBTNActionPerformed

    private void mitarbeiterTBLPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mitarbeiterTBLPropertyChange
        int spaltenNrTMP;
        boolean isVorhanden = false;
        try
        {   spaltenNrTMP = mitarbeiterTBL.getSelectedRow();
            
            ListIterator einIterator = aenderungen.listIterator();
            while(einIterator.hasNext())
            {
                if(spaltenNrTMP == Integer.parseInt(einIterator.next().toString()))
                {
                    isVorhanden = true;
                }
            }
            
            if(!isVorhanden)
            {
                aenderungen.add(spaltenNrTMP);
            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_mitarbeiterTBLPropertyChange

    private void bearbeitenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bearbeitenBTNActionPerformed
        ListIterator einIterator = aenderungen.listIterator();
        MitarbeiterVerwaltung eineVerwaltung = new MitarbeiterVerwaltung();
        int pNr, spaltenNr;
        String nachname,vorname,gDatum,strasse,plz,ort,telNr;
        boolean taetig;
        
        while(einIterator.hasNext())
        {
            spaltenNr = Integer.parseInt(einIterator.next().toString());
            if(spaltenNr!=-1)
            {
            pNr = Integer.parseInt(mitarbeiterTBL.getValueAt(spaltenNr, 0).toString());
            nachname = mitarbeiterTBL.getValueAt(spaltenNr, 1).toString();
            vorname = mitarbeiterTBL.getValueAt(spaltenNr, 2).toString();
            gDatum = mitarbeiterTBL.getValueAt(spaltenNr, 3).toString();
            strasse = mitarbeiterTBL.getValueAt(spaltenNr, 4).toString();
            plz = mitarbeiterTBL.getValueAt(spaltenNr, 5).toString();
            ort = mitarbeiterTBL.getValueAt(spaltenNr, 6).toString();
            telNr = mitarbeiterTBL.getValueAt(spaltenNr, 7).toString();
            taetig = Boolean.parseBoolean(mitarbeiterTBL.getValueAt(spaltenNr, 9).toString());
            eineVerwaltung.update(pNr,nachname,vorname,gDatum,strasse,plz,ort,telNr,taetig);
            }
        }
    }//GEN-LAST:event_bearbeitenBTNActionPerformed

    private void suchenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suchenBTNActionPerformed
        suchen();
    }//GEN-LAST:event_suchenBTNActionPerformed
    
    public void suchen()
    {
        MitarbeiterVerwaltung eineVerwaltung = new MitarbeiterVerwaltung();
        LinkedList eineListe = null;
       
        if(gruppeComboBox.getSelectedIndex()==0)
        {
            eineListe = eineVerwaltung.SuchenPnr(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==1)
        {
            eineListe = eineVerwaltung.SuchenName(begriffText.getText());
        }

        ListIterator einIterator = eineListe.listIterator();
        int i=0;
        
       // <editor-fold defaultstate="collapsed" desc=" Tabellen Modell ">
        String[] titel = {"Personal Nr", "Nachname", "Vorname", "Geburtsdatum", "Strasse", "PLZ", "Ort", "Telefon Nr", "Aufgabenbereich", "Ist T�tig"};
        boolean[] canEdit = {false, true, true, true, true, true, true, true, true, true};
        Class[] types = {Integer.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, String.class, Boolean.class};
        
        TabellenModell einModell = new TabellenModell(eineListe.size(), titel, canEdit, types);
        mitarbeiterTBL.setModel(einModell);
        // </editor-fold>  
        
        while(einIterator.hasNext())
        {
            Mitarbeiter einMitarbeiter = (Mitarbeiter)einIterator.next();
            mitarbeiterTBL.setValueAt(einMitarbeiter.getPersonalNR(),i,0);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getNachname(),i,1);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getVorname(),i,2);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getGDate(),i,3);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getStrasse(),i,4);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getPLZ(),i,5);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getOrt(),i,6);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getTelefonNr(),i,7);
            mitarbeiterTBL.setValueAt(einMitarbeiter.getIsTaetig(),i,9);
            i++;
        }
    }
    
    
    private void ausblendenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausblendenBTNActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ausblendenBTNActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ausblendenBTN;
    private javax.swing.JButton bearbeitenBTN;
    private javax.swing.JTextField begriffText;
    private javax.swing.JComboBox gruppeComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loeschenBTN;
    private javax.swing.JTable mitarbeiterTBL;
    private javax.swing.JButton suchenBTN;
    // End of variables declaration//GEN-END:variables
    
}
