/*
 * MitarbeiterIFrame.java
 *
 * Created on 20. Mai 2005, 20:48
 */

package GUI;
import FK.*;
import java.util.*;

public class RechnungIFrame extends javax.swing.JInternalFrame {
    
    private startGUI einAufrufer;
    private LinkedList aenderungen = new LinkedList();
    /** Creates new form MitarbeiterIFrame */
    public RechnungIFrame() {
        initComponents();
        //this.setSize(800,460);
        this.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rechnungTBL = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        begriffText = new javax.swing.JTextField();
        gruppeComboBox = new javax.swing.JComboBox();
        suchenBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        kundenBTN = new javax.swing.JButton();
        reservierungBTN = new javax.swing.JButton();
        bearbeitenBTN = new javax.swing.JButton();
        loeschenBTN = new javax.swing.JButton();
        ausblendenBTN = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rechnung");
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(800, 560));
        rechnungTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rechnungs Nr", "Kunden Nr", "Reservierungs Nr", "Mahnungen", "Offen", "Endabnahme", "Rechnungsbetrag"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rechnungTBL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rechnungTBLPropertyChange(evt);
            }
        });

        jScrollPane1.setViewportView(rechnungTBL);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        begriffText.setMinimumSize(new java.awt.Dimension(11, 23));
        begriffText.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel1.add(begriffText);

        gruppeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rechnungs Nr", "Kunden Nr", "Reservierungs Nr", "Offen", "Endabnahme" }));
        gruppeComboBox.setPreferredSize(null);
        jPanel1.add(gruppeComboBox);

        suchenBTN.setText("Suchen");
        suchenBTN.setPreferredSize(new java.awt.Dimension(80, 23));
        suchenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suchenBTNActionPerformed(evt);
            }
        });

        jPanel1.add(suchenBTN);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        kundenBTN.setText("Kunden");
        jPanel2.add(kundenBTN);

        reservierungBTN.setText("Reservierung");
        jPanel2.add(reservierungBTN);

        bearbeitenBTN.setText("Speichern");
        bearbeitenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bearbeitenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(bearbeitenBTN);

        loeschenBTN.setText("L\u00f6schen");
        jPanel2.add(loeschenBTN);

        ausblendenBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        ausblendenBTN.setIcon(new javax.swing.ImageIcon("Ausblenden"));
        ausblendenBTN.setText("Ausblenden");
        ausblendenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausblendenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(ausblendenBTN);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void bearbeitenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bearbeitenBTNActionPerformed
        ListIterator einIterator = aenderungen.listIterator();
        RechnungsVerwaltung eineVerwaltung = new RechnungsVerwaltung();
        int rNr, spaltenNr;
        boolean isOffen, endabnahme;
        
        while(einIterator.hasNext())
        {
            spaltenNr = Integer.parseInt(einIterator.next().toString());
            if(spaltenNr!=-1)
            {
                rNr = Integer.parseInt(rechnungTBL.getValueAt(spaltenNr, 0).toString());
                isOffen = Boolean.parseBoolean(rechnungTBL.getValueAt(spaltenNr, 4).toString());
                endabnahme = Boolean.parseBoolean(rechnungTBL.getValueAt(spaltenNr, 5).toString());
                eineVerwaltung.update(rNr,isOffen,endabnahme);
            }
        }
    }//GEN-LAST:event_bearbeitenBTNActionPerformed

    private void rechnungTBLPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rechnungTBLPropertyChange
        int spaltenNrTMP;
        boolean isVorhanden = false;
        try
        {   spaltenNrTMP = rechnungTBL.getSelectedRow();
            
            ListIterator einIterator = aenderungen.listIterator();
            while(einIterator.hasNext())
            {
                if(spaltenNrTMP == Integer.parseInt(einIterator.next().toString()))
                {
                    isVorhanden = true;
                }
            }
            
            if(!isVorhanden)
            {
                aenderungen.add(spaltenNrTMP);
            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_rechnungTBLPropertyChange

    private void suchenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suchenBTNActionPerformed
       suchen();
    }//GEN-LAST:event_suchenBTNActionPerformed

    private void ausblendenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausblendenBTNActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ausblendenBTNActionPerformed

     public void setBegriff(String value)
    {
        begriffText.setText(value);
    }
    
    public void setGruppe(int gruppe)
    {
        gruppeComboBox.setSelectedIndex(gruppe);
    }
    
    public void suchen()
    {
        RechnungsVerwaltung eineVerwaltung = new RechnungsVerwaltung();
        LinkedList eineListe = null;
        if(gruppeComboBox.getSelectedIndex()==0)
        {
            eineListe = eineVerwaltung.SuchenRechnung(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==1)
        {
            eineListe = eineVerwaltung.SuchenKnr(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==2)
        {
            eineListe = eineVerwaltung.SuchenReservierung(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==3)
        {
            eineListe = eineVerwaltung.SuchenOffen();
        }
        if(gruppeComboBox.getSelectedIndex()==4)
        {
            eineListe = eineVerwaltung.SuchenEndabnahme();
        }
        
        ListIterator einIterator = eineListe.listIterator();
        int i=0;
        
        // <editor-fold defaultstate="collapsed" desc=" Tabellen Modell ">
        String[] titel = {"Rechnungs Nr", "Kunden Nr", "Reservierungs Nr", "Mahnungen", "Offen", "Enabnahme", "Rechnungsbetrag"};
        boolean[] canEdit = {false, false, false, false, true, true, false};
        Class[] types = {Integer.class, Integer.class, Integer.class, Integer.class, Boolean.class, Boolean.class, String.class};
        
        TabellenModell einModell = new TabellenModell(eineListe.size(), titel, canEdit, types);
        rechnungTBL.setModel(einModell);
        // </editor-fold>    
        
        while(einIterator.hasNext())
        {
            Rechnung eineRechnung = (Rechnung)einIterator.next();
            rechnungTBL.setValueAt(eineRechnung.getRechnungsNR(),i,0);
            rechnungTBL.setValueAt(eineRechnung.getKundenNr(),i,1);
            rechnungTBL.setValueAt(eineRechnung.getReservierungsNr(), i, 2);
            rechnungTBL.setValueAt(eineRechnung.getAnzahlMahnungen(), i , 3);
            rechnungTBL.setValueAt(eineRechnung.getIsOffen(),i, 4);
            rechnungTBL.setValueAt(eineRechnung.getEndabnahmeErfolg(),i, 5);
            rechnungTBL.setValueAt(eineRechnung.getRechnungsbetrag(),i, 6);
            
            i++;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ausblendenBTN;
    private javax.swing.JButton bearbeitenBTN;
    private javax.swing.JTextField begriffText;
    private javax.swing.JComboBox gruppeComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kundenBTN;
    private javax.swing.JButton loeschenBTN;
    private javax.swing.JTable rechnungTBL;
    private javax.swing.JButton reservierungBTN;
    private javax.swing.JButton suchenBTN;
    // End of variables declaration//GEN-END:variables
    
}
