/*
 * RechnungenAufgabenIFrame.java
 *
 * Created on 2. Juni 2005, 09:57
 */

package GUI;

import FK.*;
import java.util.*;

public class RechnungenAufgabenIFrame extends javax.swing.JInternalFrame {
    
    /** Creates new form RechnungenAufgabenIFrame */
    public RechnungenAufgabenIFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rechnungAufgabeTBL = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ausblendenBTN = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Aufgaben Rechnungen");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        rechnungAufgabeTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Erstellen", "Art", "Kundennummer", "Reservierungsnummer", "Betrag"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rechnungAufgabeTBL);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Erstellen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        ausblendenBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        ausblendenBTN.setIcon(new javax.swing.ImageIcon("Ausblenden"));
        ausblendenBTN.setText("Ausblenden");
        ausblendenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausblendenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(ausblendenBTN);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
       {
        boolean erstellen = false;
        Rechnung eineRechnung;
        RechnungsVerwaltung eineVerwaltung = new RechnungsVerwaltung();
        int kundenNr, reservierungsNr, art;
        float rechnungsbetrag;
        
        for(int i=0; i<rechnungAufgabeTBL.getRowCount(); i++)
        {
            erstellen = Boolean.parseBoolean(rechnungAufgabeTBL.getValueAt(i, 0).toString());
            if(erstellen)
            {
                if(rechnungAufgabeTBL.getValueAt(i, 1).toString().equals("Anzahlung"))
                {
                    art=1;
                }
                else
                {
                    art=2;
                }
                kundenNr = Integer.parseInt(rechnungAufgabeTBL.getValueAt(i, 2).toString());
                reservierungsNr = Integer.parseInt(rechnungAufgabeTBL.getValueAt(i, 3).toString());
                rechnungsbetrag = Float.parseFloat(rechnungAufgabeTBL.getValueAt(i, 4).toString());
                eineRechnung = new Rechnung(kundenNr, reservierungsNr, rechnungsbetrag);
                eineRechnung.Speichern(art);
                eineVerwaltung.addRechnung(eineRechnung);
            }
        }
        tblAufbauen();
       }
       catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        tblAufbauen();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tblAufbauen()
    {
        Reservierungsverwaltung eineVerwaltung = new Reservierungsverwaltung();
        LinkedList eineListe, eineListe2 = null;
        ListIterator einIterator, einIterator2;
        int laenge;
        
        eineListe = eineVerwaltung.sucheRechnungsNr1();
        einIterator = eineListe.listIterator();
        
        eineListe2 = eineVerwaltung.sucheRechnungsNr2();
        einIterator2 = eineListe2.listIterator();
        
        laenge = eineListe.size() + eineListe2.size();
        int i=0;
        
        // <editor-fold defaultstate="collapsed" desc=" Tabellen Modell ">
        String[] titel = {"Erstellen", "Art", "Kundennummer", "Reservierungsnummer", "Betrag"};
        boolean[] canEdit = {true, false, false, false, false};
        Class[] types = {Boolean.class, String.class, Integer.class, Integer.class, Float.class};
        
        TabellenModell einModell = new TabellenModell(laenge, titel, canEdit, types);
        rechnungAufgabeTBL.setModel(einModell);
        // </editor-fold>  
        
        while(einIterator.hasNext())
        {
            Reservierung eineReservierung = (Reservierung)einIterator.next();
            //Sonst bekommen wir beim auslesen NullPointerException
            rechnungAufgabeTBL.setValueAt(true, i, 0);
            rechnungAufgabeTBL.setValueAt(false, i, 0);
            rechnungAufgabeTBL.setValueAt("Anzahlung",i,1);
            rechnungAufgabeTBL.setValueAt(eineReservierung.getKundenNR(),i,2);
            rechnungAufgabeTBL.setValueAt(eineReservierung.getResNR(),i,3);
            rechnungAufgabeTBL.setValueAt(eineReservierung.getAnzahlungsbetrag(),i,4);
 
            i++;
        }
        
        while(einIterator2.hasNext())
        {
            Reservierung eineReservierung = (Reservierung)einIterator2.next();
            //Sonst bekommen wir beim auslesen NullPointerException
            rechnungAufgabeTBL.setValueAt(true, i, 0);
            rechnungAufgabeTBL.setValueAt(false, i, 0);
            rechnungAufgabeTBL.setValueAt("Endabrechnung",i,1);
            rechnungAufgabeTBL.setValueAt(eineReservierung.getKundenNR(),i,2);
            rechnungAufgabeTBL.setValueAt(eineReservierung.getResNR(),i,3);
            rechnungAufgabeTBL.setValueAt(eineReservierung.getRechnungsbetrag(),i,4);
 
            i++;
        }
    }
    
    private void ausblendenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausblendenBTNActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ausblendenBTNActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ausblendenBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rechnungAufgabeTBL;
    // End of variables declaration//GEN-END:variables
    
}
