/*
 * ReservierungenIFrame.java
 *
 * Created on 20. Mai 2005, 20:50
 */

package GUI;
import FK.*;
import java.util.*;
import javax.swing.*;

public class ReservierungenIFrame extends javax.swing.JInternalFrame {

    private startGUI einAufrufer;
    
    /** Creates new form ReservierungenIFrame */
    public ReservierungenIFrame() {
        initComponents();
        this.setVisible(false);
    }
    
    public ReservierungenIFrame(startGUI aufrufer) {
        initComponents();
        einAufrufer = aufrufer;
        this.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        reservierungTBL = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        begriffText = new javax.swing.JTextField();
        gruppeComboBox = new javax.swing.JComboBox();
        suchenBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rechnungBTN = new javax.swing.JButton();
        kundeBTN = new javax.swing.JButton();
        mietobjektBTN = new javax.swing.JButton();
        loeschenBTN = new javax.swing.JButton();
        ausblendenBTN = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reservierungen");
        reservierungTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservierungs Nr", "Mietobjekt Nr", "Kunden Nr", "Von", "Bis", "Rechnungs Nr 1", "Rechnungs Nr 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reservierungTBL);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        begriffText.setMinimumSize(new java.awt.Dimension(11, 23));
        begriffText.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel1.add(begriffText);

        gruppeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reservierungs Nr", "Mietobjekt Nr", "Kunden Nr", "Rechnungs Nr" }));
        gruppeComboBox.setMinimumSize(new java.awt.Dimension(140, 18));
        gruppeComboBox.setPreferredSize(new java.awt.Dimension(140, 23));
        jPanel1.add(gruppeComboBox);

        suchenBTN.setText("Suchen");
        suchenBTN.setPreferredSize(new java.awt.Dimension(80, 23));
        suchenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suchenBTNActionPerformed(evt);
            }
        });

        jPanel1.add(suchenBTN);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        rechnungBTN.setText("Rechnung");
        rechnungBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungBTNActionPerformed(evt);
            }
        });

        jPanel2.add(rechnungBTN);

        kundeBTN.setText("Kunde");
        kundeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kundeBTNActionPerformed(evt);
            }
        });

        jPanel2.add(kundeBTN);

        mietobjektBTN.setText("Mietobjekt");
        mietobjektBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mietobjektBTNActionPerformed(evt);
            }
        });

        jPanel2.add(mietobjektBTN);

        loeschenBTN.setText("L\u00f6schen");
        loeschenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loeschenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(loeschenBTN);

        ausblendenBTN.setFont(new java.awt.Font("Tahoma", 0, 12));
        ausblendenBTN.setIcon(new javax.swing.ImageIcon("Ausblenden"));
        ausblendenBTN.setText("Ausblenden");
        ausblendenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausblendenBTNActionPerformed(evt);
            }
        });

        jPanel2.add(ausblendenBTN);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void rechnungBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungBTNActionPerformed
        String resNr;
        resNr = reservierungTBL.getValueAt(reservierungTBL.getSelectedRow(), 0).toString();
        einAufrufer.rechnungenAnzeigen(resNr ,2);
    }//GEN-LAST:event_rechnungBTNActionPerformed

    private void loeschenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loeschenBTNActionPerformed
        Reservierungsverwaltung eineVerwaltung = new Reservierungsverwaltung();
        int i = eineVerwaltung.loeschen(Integer.parseInt(reservierungTBL.getValueAt(reservierungTBL.getSelectedRow(), 0).toString()));
        suchen();
        if(i==-1)
        {
            JOptionPane.showMessageDialog(this, "Reservierung konnte nicht geloescht werden!", "Warnung", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_loeschenBTNActionPerformed

    private void suchenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suchenBTNActionPerformed
       suchen();
    }//GEN-LAST:event_suchenBTNActionPerformed

    private void kundeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kundeBTNActionPerformed
        String knr;
        knr = reservierungTBL.getValueAt(reservierungTBL.getSelectedRow(), 2).toString();
        einAufrufer.kundenAnzeigen(knr ,0);
    }//GEN-LAST:event_kundeBTNActionPerformed

    private void mietobjektBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mietobjektBTNActionPerformed
        String knr;
        knr = reservierungTBL.getValueAt(reservierungTBL.getSelectedRow(), 1).toString();
        einAufrufer.mietobjektAnzeigen(knr ,0);
    }//GEN-LAST:event_mietobjektBTNActionPerformed

    private void ausblendenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausblendenBTNActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ausblendenBTNActionPerformed
    
    public void setBegriff(String value)
    {
        begriffText.setText(value);
    }
    
    public void setGruppe(int gruppe)
    {
        gruppeComboBox.setSelectedIndex(gruppe);
    }
    
    public void suchen()
    {
        Reservierungsverwaltung eineVerwaltung = new Reservierungsverwaltung();
        LinkedList eineListe = null;
        
        if(gruppeComboBox.getSelectedIndex()==0)
        {
            eineListe = eineVerwaltung.sucheReservierung(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==1)
        {
            eineListe = eineVerwaltung.sucheMietobjekt(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==2)
        {
            eineListe = eineVerwaltung.sucheKunde(Integer.parseInt(begriffText.getText()));
        }
        if(gruppeComboBox.getSelectedIndex()==3)
        {
            eineListe = eineVerwaltung.sucheRechnung(Integer.parseInt(begriffText.getText()));
        }

        ListIterator einIterator = eineListe.listIterator();
        int i=0;
        
       // <editor-fold defaultstate="collapsed" desc=" Tabellen Modell ">
        String[] titel = {"Reservierungs Nr", "Mietobjekt Nr", "Kunden Nr", "Von", "Bis", "Rechnungs Nr 1", "Rechnungs Nr 2"};
        boolean[] canEdit = {false, false, false, false, false, false, false};
        Class[] types = {Integer.class, Integer.class, Integer.class, String.class, String.class, Integer.class, Integer.class};
        
        TabellenModell einModell = new TabellenModell(eineListe.size(), titel, canEdit, types);
        reservierungTBL.setModel(einModell);
        // </editor-fold>  
        
        while(einIterator.hasNext())
        {
            Reservierung eineReservierung = (Reservierung)einIterator.next();
            reservierungTBL.setValueAt(eineReservierung.getResNR(),i,0);
            reservierungTBL.setValueAt(eineReservierung.getMietobjektNr(),i,1);
            reservierungTBL.setValueAt(eineReservierung.getKundenNR(),i,2);
            reservierungTBL.setValueAt(eineReservierung.getMieteVon(),i,3);
            reservierungTBL.setValueAt(eineReservierung.getMieteBis(),i,4);
            reservierungTBL.setValueAt(eineReservierung.getRechnungsNr1(),i,5);
            reservierungTBL.setValueAt(eineReservierung.getRechnungsNr2(),i,6);
            i++;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ausblendenBTN;
    private javax.swing.JTextField begriffText;
    private javax.swing.JComboBox gruppeComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kundeBTN;
    private javax.swing.JButton loeschenBTN;
    private javax.swing.JButton mietobjektBTN;
    private javax.swing.JButton rechnungBTN;
    private javax.swing.JTable reservierungTBL;
    private javax.swing.JButton suchenBTN;
    // End of variables declaration//GEN-END:variables
    
}
