/*
 * startGUI.java
 *
 * Created on 20. Mai 2005, 19:36
 */

package GUI;

import javax.swing.JDesktopPane;

public class startGUI extends javax.swing.JFrame {
    private MitarbeiterAufgIFrame mitarbeiterAufgFrame;
    private KundenIFrame kundenFrame;
    private MitarbeiterIFrame mitarbeiterFrame;
    private ReservierungenIFrame reservierungenFrame;
    private MietobjektIFrame mietobjektFrame;
    private RechnungIFrame rechnungFrame;
    private RechnungenAufgabenIFrame rechnungenAufgabenFrame;
    private MahnungenAufgabenIFrame mahnungenAufgabenFrame;
    
    
    /** Creates new form startGUI */
    public startGUI() {
        initComponents();
        this.setSize(800,600);
        this.show();
        
        kundenFrame = new KundenIFrame(this);
        jDesktopPane1.add(kundenFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        mitarbeiterFrame = new MitarbeiterIFrame();
        jDesktopPane1.add(mitarbeiterFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        reservierungenFrame = new ReservierungenIFrame(this);
        jDesktopPane1.add(reservierungenFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
       
        mietobjektFrame = new MietobjektIFrame();
        jDesktopPane1.add(mietobjektFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        rechnungFrame = new RechnungIFrame();
        jDesktopPane1.add(rechnungFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        mitarbeiterAufgFrame = new MitarbeiterAufgIFrame();
        jDesktopPane1.add(mitarbeiterAufgFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        rechnungenAufgabenFrame = new RechnungenAufgabenIFrame();
        jDesktopPane1.add(rechnungenAufgabenFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        mahnungenAufgabenFrame = new MahnungenAufgabenIFrame();
        jDesktopPane1.add(mahnungenAufgabenFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        kundenBTN = new javax.swing.JButton();
        reservierungBTN = new javax.swing.JButton();
        mitarbeiterBTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        dateiMNU = new javax.swing.JMenu();
        beendenMNI = new javax.swing.JMenuItem();
        reservierungenMNU = new javax.swing.JMenu();
        rerfassenMNI = new javax.swing.JMenuItem();
        kundenMNU = new javax.swing.JMenu();
        erfassenMNI = new javax.swing.JMenuItem();
        mitarbeiterMNU = new javax.swing.JMenu();
        mErfassenMNI = new javax.swing.JMenuItem();
        immobilienMNU = new javax.swing.JMenu();
        iErfassenMNI = new javax.swing.JMenuItem();
        aufgabenMNU = new javax.swing.JMenu();
        mitarbeiterAufgMNI = new javax.swing.JMenuItem();
        rechnungenAufgMNI = new javax.swing.JMenuItem();
        mahnungenAufgMNI = new javax.swing.JMenuItem();
        fensterMNU = new javax.swing.JMenu();
        ueberlappentMNI = new javax.swing.JMenuItem();
        untereinnanderMNI = new javax.swing.JMenuItem();
        nebeneinnanderMNI = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        symboleAnordnenMNI = new javax.swing.JMenuItem();
        alleSchliessenMNI = new javax.swing.JMenuItem();
        aboutMNU = new javax.swing.JMenu();
        aboutITM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ferienwohnungsverwaltung");
        setFocusable(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        kundenBTN.setText("Kunden");
        kundenBTN.setPreferredSize(null);
        kundenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kundenBTNActionPerformed(evt);
            }
        });

        jPanel1.add(kundenBTN);

        reservierungBTN.setText("Reservierungen");
        reservierungBTN.setPreferredSize(null);
        reservierungBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservierungBTNActionPerformed(evt);
            }
        });

        jPanel1.add(reservierungBTN);

        mitarbeiterBTN.setText("Mitarbeiter");
        mitarbeiterBTN.setPreferredSize(null);
        mitarbeiterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterBTNActionPerformed(evt);
            }
        });

        jPanel1.add(mitarbeiterBTN);

        jButton1.setText("Mietobjekt");
        jButton1.setPreferredSize(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);

        jButton2.setText("Rechnungen");
        jButton2.setPreferredSize(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        dateiMNU.setText("Datei");
        beendenMNI.setText("Beenden");
        beendenMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beendenMNIActionPerformed(evt);
            }
        });

        dateiMNU.add(beendenMNI);

        jMenuBar1.add(dateiMNU);

        reservierungenMNU.setText("Reservierungen");
        rerfassenMNI.setText("Erfassen");
        rerfassenMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerfassenMNIActionPerformed(evt);
            }
        });

        reservierungenMNU.add(rerfassenMNI);

        jMenuBar1.add(reservierungenMNU);

        kundenMNU.setText("Kunden");
        erfassenMNI.setText("Erfassen");
        erfassenMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erfassenMNIActionPerformed(evt);
            }
        });

        kundenMNU.add(erfassenMNI);

        jMenuBar1.add(kundenMNU);

        mitarbeiterMNU.setText("Mitarbeiter");
        mErfassenMNI.setText("Erfassen");
        mErfassenMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mErfassenMNIActionPerformed(evt);
            }
        });

        mitarbeiterMNU.add(mErfassenMNI);

        jMenuBar1.add(mitarbeiterMNU);

        immobilienMNU.setText("Immobilien");
        iErfassenMNI.setText("Erfassen");
        iErfassenMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iErfassenMNIActionPerformed(evt);
            }
        });

        immobilienMNU.add(iErfassenMNI);

        jMenuBar1.add(immobilienMNU);

        aufgabenMNU.setText("Aufgaben");
        mitarbeiterAufgMNI.setText("Mitarbeiter");
        mitarbeiterAufgMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterAufgMNIActionPerformed(evt);
            }
        });

        aufgabenMNU.add(mitarbeiterAufgMNI);

        rechnungenAufgMNI.setText("Rechnungen");
        rechnungenAufgMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungenAufgMNIActionPerformed(evt);
            }
        });

        aufgabenMNU.add(rechnungenAufgMNI);

        mahnungenAufgMNI.setText("Mahnungen");
        mahnungenAufgMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahnungenAufgMNIActionPerformed(evt);
            }
        });

        aufgabenMNU.add(mahnungenAufgMNI);

        jMenuBar1.add(aufgabenMNU);

        fensterMNU.setText("Fenster");
        fensterMNU.setEnabled(false);
        ueberlappentMNI.setText("\u00dcberlappend");
        fensterMNU.add(ueberlappentMNI);

        untereinnanderMNI.setText("Untereinnander");
        fensterMNU.add(untereinnanderMNI);

        nebeneinnanderMNI.setText("Nebeneinnander");
        fensterMNU.add(nebeneinnanderMNI);

        fensterMNU.add(jSeparator1);

        symboleAnordnenMNI.setText("Symbole anordnen");
        fensterMNU.add(symboleAnordnenMNI);

        alleSchliessenMNI.setText("Alle schlie\u00dfen");
        fensterMNU.add(alleSchliessenMNI);

        jMenuBar1.add(fensterMNU);

        aboutMNU.setText("?");
        aboutITM.setText("About");
        aboutITM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutITMActionPerformed(evt);
            }
        });

        aboutMNU.add(aboutITM);

        jMenuBar1.add(aboutMNU);

        setJMenuBar(jMenuBar1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void aboutITMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutITMActionPerformed
        About einDialog = new About(this, true);
        einDialog.setSize(520, 430);
        einDialog.setVisible(true);
    }//GEN-LAST:event_aboutITMActionPerformed

    private void mahnungenAufgMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahnungenAufgMNIActionPerformed
    try {       
            mahnungenAufgabenFrame.setMaximum(true);
            mahnungenAufgabenFrame.setVisible(true);  
            mahnungenAufgabenFrame.moveToFront();
    }
    catch (Exception e)
    {}
    }//GEN-LAST:event_mahnungenAufgMNIActionPerformed

    private void rechnungenAufgMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungenAufgMNIActionPerformed
    try {       
            rechnungenAufgabenFrame.setMaximum(true);
            rechnungenAufgabenFrame.setVisible(true);  
            rechnungenAufgabenFrame.moveToFront();
    }
    catch (Exception e)
    {}
    }//GEN-LAST:event_rechnungenAufgMNIActionPerformed

    private void mitarbeiterAufgMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterAufgMNIActionPerformed
    try {       
        mitarbeiterAufgFrame.setMaximum(true);
        mitarbeiterAufgFrame.setVisible(true);  
        mitarbeiterAufgFrame.moveToFront();
    }
    catch (Exception e)
    {}
    }//GEN-LAST:event_mitarbeiterAufgMNIActionPerformed

    private void rerfassenMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerfassenMNIActionPerformed
         reservierungErfassenAnzeigen("");
    }//GEN-LAST:event_rerfassenMNIActionPerformed
    
    public void reservierungErfassenAnzeigen(String knr)
    {
        ReservierungErfassenDIA reservierungErfassen = new ReservierungErfassenDIA(this, true, knr); 
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            rechnungFrame.setMaximum(true);
            rechnungFrame.setVisible(true);  
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            mietobjektFrame.setMaximum(true);
            mietobjektFrame.setVisible(true);  
            mietobjektFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reservierungBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservierungBTNActionPerformed
        try
        {
            reservierungenFrame.setMaximum(true);
            reservierungenFrame.setVisible(true);  
            reservierungenFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_reservierungBTNActionPerformed

    public void reservierungenAnzeigen(String value, int gruppe)
    {
        try
        {
            reservierungenFrame.setBegriff(value);
            reservierungenFrame.setGruppe(gruppe);
            reservierungenFrame.suchen();
            reservierungenFrame.setMaximum(true);
            reservierungenFrame.setVisible(true);
            reservierungenFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }
    
    public void rechnungenAnzeigen(String value, int gruppe)
    {
        try
        {
            rechnungFrame.setBegriff(value);
            rechnungFrame.setGruppe(gruppe);
            rechnungFrame.suchen();
            rechnungFrame.setMaximum(true);
            rechnungFrame.setVisible(true); 
            rechnungFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }
    
    public void kundenAnzeigen(String value, int gruppe)
    {
        try
        {
            kundenFrame.setBegriff(value);
            kundenFrame.setGruppe(gruppe);
            kundenFrame.suchen();
            kundenFrame.setMaximum(true);
            kundenFrame.setVisible(true); 
            kundenFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }
    
    public void mietobjektAnzeigen(String value, int gruppe)
    {
        try
        {
            mietobjektFrame.setBegriff(value);
            mietobjektFrame.setGruppe(gruppe);
            mietobjektFrame.suchen();
            mietobjektFrame.setMaximum(true);
            mietobjektFrame.setVisible(true); 
            mietobjektFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }
    
    private void iErfassenMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iErfassenMNIActionPerformed
        ImmobilieErfassenDIA immobilieErfassen = new ImmobilieErfassenDIA(this, true);     
    }//GEN-LAST:event_iErfassenMNIActionPerformed

    private void mErfassenMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mErfassenMNIActionPerformed
        MitarbeiterErfassenDIA mitarbeiterErfassen = new MitarbeiterErfassenDIA(this, true);
    }//GEN-LAST:event_mErfassenMNIActionPerformed

    private void erfassenMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erfassenMNIActionPerformed
        KundeErfassenDIA kundeErfassen = new KundeErfassenDIA(this, true);
        
    }//GEN-LAST:event_erfassenMNIActionPerformed

    private void kundenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kundenBTNActionPerformed
        try
        {
            kundenFrame.setMaximum(true);
            kundenFrame.setVisible(true);
            kundenFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_kundenBTNActionPerformed

    private void beendenMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beendenMNIActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_beendenMNIActionPerformed

    private void mitarbeiterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterBTNActionPerformed
        try
        {
            mitarbeiterFrame.setMaximum(true);
            mitarbeiterFrame.setVisible(true);  
            mitarbeiterFrame.moveToFront();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_mitarbeiterBTNActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startGUI().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutITM;
    private javax.swing.JMenu aboutMNU;
    private javax.swing.JMenuItem alleSchliessenMNI;
    private javax.swing.JMenu aufgabenMNU;
    private javax.swing.JMenuItem beendenMNI;
    private javax.swing.JMenu dateiMNU;
    private javax.swing.JMenuItem erfassenMNI;
    private javax.swing.JMenu fensterMNU;
    private javax.swing.JMenuItem iErfassenMNI;
    private javax.swing.JMenu immobilienMNU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kundenBTN;
    private javax.swing.JMenu kundenMNU;
    private javax.swing.JMenuItem mErfassenMNI;
    private javax.swing.JMenuItem mahnungenAufgMNI;
    private javax.swing.JMenuItem mitarbeiterAufgMNI;
    private javax.swing.JButton mitarbeiterBTN;
    private javax.swing.JMenu mitarbeiterMNU;
    private javax.swing.JMenuItem nebeneinnanderMNI;
    private javax.swing.JMenuItem rechnungenAufgMNI;
    private javax.swing.JMenuItem rerfassenMNI;
    private javax.swing.JButton reservierungBTN;
    private javax.swing.JMenu reservierungenMNU;
    private javax.swing.JMenuItem symboleAnordnenMNI;
    private javax.swing.JMenuItem ueberlappentMNI;
    private javax.swing.JMenuItem untereinnanderMNI;
    // End of variables declaration//GEN-END:variables
    
}